### ISSUE TITLE
Test the extension

### ISSUE THREAD

**Issue by lovasoa** [lovasoa/dezoomify-extension#1]
# We need beta-testers

Version 0.1 of the extension has been published.
Now we need users to test it and report issues.
Do not hesitate to install the extension and give us feedback in this thread.

In particular, I would be interested in the following feedback : 
 - did you feel like the extension slows your browser down ?
 - does it activate on web pages where it shouldn't ?
 -  does it fail to activate on web pages that contain zoomable images ?
 - Can you help write a good description for the extension in english ?

Donwload the extension [for Firefox](https://addons.mozilla.org/en-US/firefox/addon/dezoomify/) and [for Google Chrome](https://chrome.google.com/webstore/detail/iapjjopjejpelnfdonefbffahmcndfbm).

**Comment by SB2020-eye** [comment]
Your questions, in order:
1. I don't know. But mine isn't gray any more. It's always blue. Should it be? The instructions suggest it should go back to gray and only be blue after I press it and use it.
2. I don't know.
3. It activated on http://www.bl.uk/manuscripts/Viewer.aspx?ref=cotton_ms_nero_d_iv_fs001r (The British Library). But it didn't work, in Chrome, Firefox, or dezoomify-rs.
4. Maybe so. For starters, you have a typo on "Download" in the last line of the instructions above. Let me know what you're looking for and I'll let you know if I can be of help.

All the best!

**Comment by lovasoa** [comment]
Thank you ! Are you using the extension on chrome or firefox ? Google is very slow at validating extensions, so the chrome version never has the latest features and bug fixes, and there is nothing I can do about it.

**Comment by lovasoa** [comment]
You can find our current description here: https://raw.githubusercontent.com/lovasoa/dezoomify-extension/master/README.md

If you are a native English speaker and can improve it, I would be grateful !

**Comment by lovasoa** [comment]
I opened a separate issue for the British library : https://github.com/lovasoa/dezoomify-extension/issues/4

**Comment by SB2020-eye** [comment]
I will take a look at the current description.

**Comment by SB2020-eye** [comment]
Here are my edits. They are relatively few. Since you asked for help in English, I was expecting there to be more problems. You do rather well on your own. :)
[Dezoomify-extension.txt](https://github.com/lovasoa/dezoomify-extension/files/4363787/Dezoomify-extension.txt)
[Dezoomify-extension-NOTES.txt](https://github.com/lovasoa/dezoomify-extension/files/4363790/Dezoomify-extension-NOTES.txt)

**Comment by lovasoa** [comment]
Thank you very much Scott for your contribution ! This is appreciated.

I implemented some of your changes. I'm copy-pasting them below as a summary

- [x] Online at the Dezoomify page, your instructions include the following: "If it doesn't work, read our FAQ. If you want more information, read our project page. This script is released under the GPL." Do you want to include any of this in the Readme? *I added a link to the FAQ*
 - [x] a. It might be nice to have a header above the images - perhaps akin to how you name it in your text file: "Animated Tutorial"
 - [x] b. The pictures go a little fast. (I had to watch through them a few times to accurately edit them! Ha!)
 - [ ] c. If it's simple, the user having some capacity for pausing it or advancing it like you see on many website home pages might be nice. But it's not imperative, as long as you slow it down.
 - [ ] d. Part of it being fast is that the user might not have a chance to locate the relatively tiny dezoomify icon. An arrow or something drawn over the image to correspond with the instructions might be of interest to you. Perhaps even with all the slides. Just an idea.
 - [ ] e. Edits from the slides' Slide1: You have "gray grey" - go with "grey", which is what you have in your instructions.
 - [ ] ii. Slide1: The font is smaller than every other slide.

 - [ ] 3. You might want to consider incorporating the latter part of your instructions into the Dezoomify tool landing page. Maybe even some small versions of the tutorial images (perhaps so it still all appears on one screen that doesn't need to be scrolled). Again - just a thought.


Many changes are required in the animated tutorial. Does someone want to contribute a nice tutorial in a collaborative form ? Maybe a google slides document that we can then turn into a GIF ?


Yes the dezoomify landing page could be much better. Your suggestions are good, I'm open to any other suggestions.

**Comment by Panamauser** [comment]
Hello,
Great tool,  keep up with  your work.
When we use the URL(https://dezoomify.ophir.dev/dezoomify/dezoomify.html)  to dezoomify pictures from this site  (https://ufdc.ufl.edu/PCMI002369/00001/59x) everything  works  smoothly.
But,  we wanted to try Google extension for the pictures in the same site, and  we have noted some issues after a couple of download. Our **Chrome version is (Versión 85.0.4183.102 (Build oficial**) (64 bits))


1.  For example,  When we downloaded  about 10 images,  the laptop started to freeze and it was not possible to run task manager _**(windows 10 Lenovo Model 20KS003LLM**_ with 8GB RamIntel(R) Core(TM) i7-8550U CPU @ 1.80GHz with 8 cores) this laptop has been working fine because it is less than 8 months of use.

2. Next day, we try to give another try,  and after downloading about 15 pictures from site above,  the same situation, the laptop stuck really bad, that we had to power off the laptop by pressing down the power button.

We have norton Antivirus installed and there is no virus detected.  We deinstalled a few extensions we had, even dezoomify and try using now the URL,  and  we have been able to download more than 40 pictures without any disturbance.

So  just to report that,  this only happens with the Google extension,  we  do not see any  error at event viewer located at this machine.

Regards.
