### ISSUE TITLE
High resource usage on chrome

### ISSUE THREAD

**Issue by lovasoa** [lovasoa/dezoomify-extension#13]
_@rhythmus reported in https://github.com/lovasoa/dezoomify/issues/428#issuecomment-699672522_

- Chrome Version 85.0.4183.83 (Official Build) (64-bit)
- Dezoomify Chrome extension, Version 0.4.3
- macOS Mojave Version 10.14.6
- URL: https://www.britishmuseum.org/collection/object/P_F-4-171

>  the extensions seems to consume lots of CPU on Chrome. My fans blow heavily and Chrome’s Task Manager shows a resource intensive process — until I deactivate the Dezoomify extension. Thought you might want to know.

**Comment by lovasoa** [comment]
I cannot reproduce the issue. @rhythmus I welcome any information that could help reproduce the issue. Does it happen systematically for you ?

**Comment by AnotherCollector** [comment]
Hello again,
I want to clarify that the issue here and my issue are a bit different, disabling the extension or uninstalling it didn't solve the problem that Chrome would stay unresponsive for about half a minute whenever I launch it and using so much ram(more than 4gb)

As for reproduction instructions:
I was trying to download these 70 images and (each is about 50 mb in size) I didn't notice any issue while the extension was working, but later on chrome started struggling

[https://digital.bodleian.ox.ac.uk/inquire/Discover/Search/#/?p=c+3,t+,rsrs+0,rsps+100,fa+,so+ox%3Asort%5Easc,scids+,pid+ced0d8bd-1019-4af2-9086-e411115f1507,vi+](url)

I also want to add, that the issue isn't with these images in particular but maybe with my extensive use of the extension so maybe it saved a lot of cache that caused the issue, still I tried cleaning Chrome cache and history.

Anyway, I have uninstalled it from Chrome and now I'm using Firefox one, I hope this can help you resolve the issue

I also want to thank you for your hard work this extension is really amazing, please keep it up!

**Comment by lovasoa** [comment]
I'm not sure I understand your problem. Do you have an issue with dezoomify (the website) or dezoomify-extension (the browser add-on) ?

**Comment by AnotherCollector** [comment]
my problem is with deezoomify-extension, I noticed Chrome freezing and struggling with high ram usage at every launch after I installed the extension and used it for some time, nothing I tried work I ended up reinstalling Chrome and it worked but when I installed the extension  once again and used it for some time the same problem occurred and I had to reinstall Chrome and switch to Firefox extension instead hoping I won't face the same issue.

**Comment by lovasoa** [comment]
Closing because of lack of response. If someone else is experimenting this, please make yourself known and we'll reopen and investigate this.
